### ISSUE TITLE
"Important Note" on examples lacks visible affordance

### ISSUE THREAD

**Issue by aardrian** [w3c/wai-aria-practices#114]
Looking at (just as a sample):
https://www.w3.org/WAI/ARIA/apg/example-index/disclosure/disclosure-navigation-hybrid.html

- At the top of the page is a light green box with a dark green bar on its left with the text "Important Note About Use of This Example".

- Immediately following it is a light gray box with a dark gray bar on its left with the text "Although this example uses the word "menu" in the colloquial sense..."

One of those boxes is interactive. There is no visual affordance indicating which one it is, other than a pointer for a mouse user or it taking focus when a keyboard-only user is tabbing through the page.

The concern is that the important note text is _hidden by default_ and the text that follows in the gray box could be reasonably construed as the important note.

My suggestion:
1. Add the same affordance used in the disclosure widget patterns (a downward-pointing arrow); or
2. Keep the browser default; or
3. Do not have the text collapsed by default.

I vote for the third option. Important notes should probably not be hidden by default since that is contradicting its claim of importance.

**Comment by mcking65** [comment]
Working on another option so that the warning is more  prominent and readily understood even when partially visible.

Looking ahead to when we start work to make the site more small-screen friendly, fully expanding does not seem ideal. Yet, we need the gist of the content to be understood without expanding. We have a pattern for the read this first content that is already used on other pages. With some slight modification to that pattern (#115), we can adapt it to fix this issue with #116. This will create more consistency across the site and should achieve the goal of making the warnings about use in production difficult to overlook.

**Comment by richnoah** [comment]
#116
