### ISSUE TITLE
Error 404 for 14 pages after deploy of restructure

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#186]
I believe the changes in #184  did not generate correct paths for the following pages. Links to the following new page locations generate 404s. Note: this is not a problem with the redirects. The redirects correctly point to these new page locations:

https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/at
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/banner
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/complementary
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/contentinfo
https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/datagrids/
https://www.w3.org/WAI/ARIA/apg/patterns/feed/examples/feedDisplay
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/form
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/index
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/html5
https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layoutgrids/
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/main
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/region
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/resources
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/search

**Comment by alflennik** [comment]
@mcking65 @howard-e I opened a PR https://github.com/w3c/wai-aria-practices/pull/187 which fixes this issue. Once it's reviewed and merged we can request a follow-on deploy from the WAI team.

Regarding two of the broken links, the datagrids link and the layoutgrids links, I didn't make any changes to those pages because the links as written above have incorrect capitalization, they should be `dataGrids` and `layoutGrids` instead of `datagrids` and `layoutgrids`. The pages within the site do have the correct capitalization so I don't think those two pages are actually broken.

Finally, there is another issue which my PR doesn't address and we still have to fix: there are now broken image links in the feedDisplay page.

That example dynamically creates images, which, as of the release yesterday, is not something we support, because on the final deploy the images will be stored in a different directory than the source code. All of the content and assets for the entire site will be split up into three groups, a content folder for html files, a content-images folder for images, and a content-assets folder for everything else.

Personally, while the site does currently work, I think the mental overhead of making sure the APG supports its html, images and assets being automatically divided up into three directories when deployed is not a good long-term solution.

**Comment by alflennik** [comment]
I looked into the datagrids and layout grids a little bit more and found that the WAI website seems to automatically remove capitalized letters from URLs. This is why the links on the site work but bookmarked pages don't.

I think the pages already have a bit of a strange naming convention, given that no other pages have capitalized letters, so a good solution would probably be to rename those two files in the aria-practices repo and introduce new redirects from the old urls to the new ones.

**Comment by mcking65** [comment]
Since the links within the site are now working, I'm closing this issue. I have opened #192 to address the 4 remaining problems related to bookmarks that yield 404s.
