### ISSUE TITLE
Example pages show incorrect revision date

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/wai-aria-practices#255]
When you run `node ./scripts/pre-build` (to generate the pages?) all the “Page last updated” lines are updated in the examples/*.md files. This causes git status to be filled with 58 changes; this is quite confusing when it comes to contributing (especially for the first time).

My steps:
1. Checkout this repo
2. Follow “Local development” from the readme for the first time
3. Be a little overwhelmed by all the changes I didn’t make popping up in `git status`

<img width="675" alt="git status shows a long list of modifications generated by the script rather than the user" src="https://github.com/w3c/wai-aria-practices/assets/5457769/6f0bba52-8950-4fd1-af84-977996371374">

Is there another time/way this date update could be done?

**Comment by mcking65** [comment]
We don't expect anyone to contribute to this repo. It is for builds only.

**Comment by alice** [comment]
I just took a quick look at this because my curiosity was piqued.

It looks like whatever process is running to generate the [bot commits](https://github.com/w3c/wai-aria-practices/commits?author=michael-n-cooper-bot) is updating every single example page to have a last updated date of whatever the current date is when the bot is run, rather than correctly getting the date the source example was last updated.

For example, [the most recent bot commit](https://github.com/w3c/wai-aria-practices/commit/2c8a217792dc5045a09cd0a0fc50e675b0379a0e) on 2 September updates [alertdialog.md](https://github.com/w3c/wai-aria-practices/commit/2c8a217792dc5045a09cd0a0fc50e675b0379a0e#diff-05bb885bd2afdd5f9d26c411c3d1deddda629a94fcc0cf5c7fa29c5fd470f271) to have a "Page last updated" date of `2 Sepember 2023`, from a previous value of `29 August 2023` which was also set incorrectly by the bot.

Running the script locally correctly edits that value to be `8 December 2022`, reflecting [the actual last update of the source file](https://github.com/w3c/aria-practices/commits/main/content/patterns/alertdialog/examples/alertdialog.html).

This is causing the live examples to all have incorrect "Page last updated" sections in the footer; currently they're all showing as "8 August 2023" (see, again, the [live page for the Alert Dialog Pattern example](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/examples/alertdialog/#wai-site-footer)).

Fixing whatever issue is causing the dates to be incorrectly set by the bot updates would fix both the issue Zoë is having (regardless of whether someone wants to commit to this repository, they may want to do a local build in order to see their changes to the [aria-practices](https://github.com/w3c/aria-practices) repo in context, and it's not a nice experience to see a bunch of irrelevant files changed), and the issue of examples having incorrect last updated timestamps.

**Comment by mcking65** [comment]
@alice 

Thank you for looking into this. Your observations are useful. We have an issue that is partially related to the incorrect dates (#87). However, it is unnecessarily tangled up with an issue related to acknowledgements.

@ZoeBijl, I'm convinced that we should address this to at least ensure the last revised info shown on each page is accurate.

Unfortunately, the revision dates won't help people know when the last substantive revision was. For that, they will still have to dig into the git logs. When we redesign the footer, I want to make it easier to access the revision history. Unfortunately, that is pretty complex for the example pages because you also need to surface the revision history of the js, css, and image files.

**Comment by ccanash** [comment]
Hi @mcking65 this was released in mid December. I have updated our project board.
