### ISSUE TITLE
Assistive Technology Support iframe element requires an accessible name

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/wai-aria-practices#263]
Example: https://www.w3.org/WAI/ARIA/apg/patterns/alert/examples/alert/#assistivetechnologysupport

According to specifications, iframe elements typically necessitate an accessibility name, with exceptions in cases where the iframe is inert or designated as purely decorative. Consequently, we have to assign an accessible name to these iframe elements.

**Comment by giacomo-petri** [comment]
I'm happy to resolve it with a PR, if it's approved, by adding a `title="Assistive Technology Support"`

**Comment by giacomo-petri** [comment]
closing, I've just realised I was in wai-aria-practices, instead of aria-practices

**Comment by mcking65** [comment]
@giacomo-petri 

If there is such a specification, it should be updated because naming iframes would typically be a problematic practice. I would be hard pressed to think of a case where an iframe should have an accessible name. iframes are not semantic structures. They are a like a div.

**Comment by mcking65** [comment]
If there is such a specification, it should be updated because naming iframes would typically be a problematic practice. I would be hard pressed to think of a case where an iframe should have an accessible name. iframes are not semantic structures. They are a like a div.

BTW, this was more appropriately in the other repo. The AT support tables are part of the content and the iframe is added to each page with an AT support table as part of the content. The iframe is not introduced by the build process.
