### ISSUE TITLE
Include string in 2nd segment of HTML title tag to indicate page is part of APG

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-aria-practices#31]
straw proposal:

> text-of-h1 | ARIA Authoring | WAI | W3C

**Comment by mcking65** [comment]
@shawna-slh 

I agree this is a very important issue, and we need to resolve it before launch.

The current HTML title is:

>text-of-h1 | WAI | W3C

To be consistent with what we have requested for the URI in #37, I'd like to suggest that we change the HTML title on all pages except the home page to:

>text-of-h1 | APG | WAI | W3C

This is another situation where brevity adds a lot of value, especially for zoom and screen reader users.

**Comment by richnoah** [comment]
@mcking65 @shawna-slh we are currently not able to add | APG | to the string.  The API takes the h1 for the page and adds | WAI | W3C to it.  We do not have a means of appending to it.  

This was after investigating the docs at https://wai-website-theme.netlify.app/writing/frontmatter/#title, the example config at https://github.com/w3c/wai-resource-template/blob/master/_config.yml, and I searched the entire WAI Resource template at https://github.com/w3c/wai-resource-template and the entire WAI theme.

An override would not work in this instance.  Both the h1 and title tag should work even if JS is turned off.  Since these elements are heavily used by search engines and bots it is advisable to not implement an override.

**Comment by shawna-slh** [comment]
@SteveALee Feel free to address this directly, or talk with me first, as you wish. :-)

**Comment by shawna-slh** [comment]
I think I updated this info somewhere, but can't find it. So I'm adding it here for the record.

My preference is to include ARIA:
> text-of-h1 | ARIA APG | WAI | W3C

Yet I'm OK without ARIA as Matt prefers:
> text-of-h1 | APG | WAI | W3C

**Comment by mcking65** [comment]
I have reviewed the preview of #62, and this issue is addressed.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
