### ISSUE TITLE
Set URI for APG in w3.org site config

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wai-aria-practices#37]
suggestion is to use /WAI/ARIA/practices/ any thoughts?

**Comment by michael-n-cooper** [comment]
This might relate to name discussion in #28 

@shawna-slh this issue is where we can collect feedback from stakeholders

**Comment by shawna-slh** [comment]
My mild preference right now is /WAI/ARIA/authoring-practices/

Considerations:
* What do current users call the current TR doc? What do they use for shorthand?
* What makes most sense to new users?

options & my initial reactions:
1. /WAI/ARIA/authoring/ &mdash; if only one word, 'authoring' seems the clearest, at least for those familiar with the WCAG concept of authoring
2. /WAI/ARIA/practices/ &mdash; 'practices' doesn't make much sense by itself.... unless it conjurers up "best practices", which we might want to avoid
3. /WAI/ARIA/authoring-practices/ &mdash; seems like the clearest, and since we don't expect people to type the URI much if at all, probably better to go with longer and clearer
4. /WAI/ARIA/APG/ &mdash; best not to use acronym unless it's well known, catchy, &/or other, which I think this is not

I don't feel strongly about any of them - for or against.

**Comment by mcking65** [comment]
Our long term roadmap is to cover authoring practices that go beyond the ARIA spec. I'd rather not "bake" ARIA into the URL.

Using the word "guide" is helpful in a lot of ways. If we don't include "guide", there is a lack of a true noun. "The Authoring Practices" is awkward wording, e.g., "Go look that up in the authoring practices." However, I hear people say, practically daily in some forum or another, "In the APG, it says ..."

Because WAI-ARIA Authoring Practices Guide is long and hard to say, people have been saying :"APG" outloud, and writing it, for years ... since the beginning really.

Because of the massive value of brief URLS that are easy to understand and remember, I personally prefer:

w3.org/wai/apg

I suppose I prefer that for the same reason that the WAI site is w3.org/wai instead of w3.org/web-accessibility-initiative

**Comment by shawna-slh** [comment]
@brewerj high-level URI proposed above. (/me will let the idea stew before commenting, after I'm back)

**Comment by brewerj** [comment]
I'm inclined towards something with meaning, given the number indecipherable acronyms we already have in this space, especially if suggesting putting this at the level of the WAI directory. 

I understanding that this work may not always be centered exclusively around ARIA, but don't know how problematic it is to keep that as a reference. 

For those reasons, I learn towards the suggestion "w3.org/WAI/ARIA/authoring"

Or possibly w3.org/WAI/ARIA/apg

But less inclined to w3.org/WAI/apg

Would not object to w3.org/WAI/ARIA/practices/

I do not need to be in the thread further.

Thanks, 
- Judy

**Comment by iadawn** [comment]
Another couple options that come to mind are:

* /WAI/ARIA/guide/
* /WAI/ARIA/guidelines/
* /WAI/ARIA/patterns/
* /WAI/ARIA/usage/

"Authoring practices" always struck me as a bit unclear but at least it made it easy to find in search engine as no one else used such terminology!

On the topic of future proofing for other authoring practices, it is difficult to comment on that as not clear what your roadmap is but I would be concerned that it is casting the net too wide. ARIA Authoring Practices (putting the specifics of the terminology aside) is largely focused on how to use ARIA attributes correctly. The inclusion of keyboard interaction isn't really about ARIA attributes but is necessary as ARIA is being used to build interactive elements.

**Comment by mcking65** [comment]
As @a11ydoer mentioned, the APG task force has discussed this at length.

The strong taskforce preference is /wai/apg 

The resource is widely known as theAPG.

Baking "ARIA" into the URI is not seen as adding value or clarity for users. Over time, as we work on adding examples where there is little or no use of explicit ARIA, i.e.,  where the accessibility semantics are implicit, including "ARIA" in the name or URI could be constraining and could even confuse people.

There is massive, almost immeasurable  value and utility in short, meaningful URIs. That is why the domain is "w3" and the parrent path is "wai". The value of brevity increases as the APG becomes increasingly important to accessibility on small touch screen devices.

Net, the task force expressed a strong preference for w3.org/wai/apg because it maximizes utility, simplicity, and clarity. That is, it is the simplest and most utilitarian expression of how to get to the "Web Accessibility Initiative Authoring Practices Guide".

@shawna-slh , does this require further discussion? Or, can @michael-n-cooper  move forward with "/wai/apg"?

**Comment by shawna-slh** [comment]
Please see [EOWG minutes from 29 April](https://www.w3.org/2022/04/29-eo-minutes.html#t02)

Basically, while "Authoring Practices" and "APG" are comfortable for those who already know the document, it does not make sense to those who are not already "in-the-know".

**Comment by shawna-slh** [comment]
If we want an interim solution for launch soon, I would be OK with title of:
> ARIA Authoring Practices Guide (APG)

and URI of:
> w3.org/WAI/ARIA/APG

(or w3.org/WAI/ARIA/apg )

-- with the agreement that we would revisit the title and the URI for later iterations.

Note that W3C has a good redirect system, so we need not be concerned with baked URIs.

**Comment by mcking65** [comment]
@michael-n-cooper, Per meeting discussion this morning, we have agreed to use w3.org/wai/aria/apg

Thank you all for the input and consideration.

@michael-n-cooper , please close this issue when all tasks related to the URI config are complete on the back-end. We are targeting a quiet launch on May 11 so that we have several days before the announcement to perform final quality checks and test the site publication process.

**Comment by michael-n-cooper** [comment]
Case-sensitive version of the URI: https://www.w3.org/WAI/ARIA/apg/

**Comment by mcking65** [comment]
@michael-n-cooper wrote:

> Case-sensitive version of the URI: https://www.w3.org/WAI/ARIA/apg/

Since APG is an acronym, like WAI and ARIA, shouldn't it be `/APG`?

So, how is case resolved in paths? can users type /wai/aria/apg/ and get to /WAI/ARIA/APG/ in the w3.org domain? I notice that when I put /wai/aria/ in the Chrome address bar, it loads the aria page abnd the address shows the all caps string.

**Comment by shawna-slh** [comment]
@iadawn Just wanted to let you know that we appreciate your input. We decided that we didn't have time to do a "rebranding" and so we would keep current title and parallel URI for now.

**Comment by iadawn** [comment]
Not a problem at all, I appreciate the challenge

**Comment by michael-n-cooper** [comment]
> @michael-n-cooper wrote:
> 
> > Case-sensitive version of the URI: https://www.w3.org/WAI/ARIA/apg/
> 
> Since APG is an acronym, like WAI and ARIA, shouldn't it be `/APG`?
> 
> So, how is case resolved in paths? can users type /wai/aria/apg/ and get to /WAI/ARIA/APG/ in the w3.org domain? I notice that when I put /wai/aria/ in the Chrome address bar, it loads the aria page abnd the address shows the all caps string.

@mcking65 I'm not sure if this has been documented publicly yet, but the Team were told recently that all new URIs should be lowercase, starting now. Existing URIs are grandfathered, which is why we have case-sensitive ones for WAI and ARIA. W3C does case redirects, so /wai/aria/apg/ (all lowercase) will work.

**Comment by michael-n-cooper** [comment]
@mcking65 Will the examples be in a subfolder /examples/? Right now they appear to be in /index/. Just want to confirm which one to give the webmaster.

**Comment by shawna-slh** [comment]
@michael-n-cooper Update: We haven't published yet. We're addressing issue getting the example files to work with the WAI site system. Hopefully we will publish later today, though maybe not until tomorrow/Friday.

Last I saw, examples are in folder /example-index/ -- however, that could have changed. Should check with Bocoup folks, e.g., @richnoah

(Safest would be to wait until we publish.)
