### ISSUE TITLE
Test href of WAI link in banner in prod

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#68]
Once the site is pushed to prod, test the banner WAI link to be sure it resolves correctly.

In netlify preview, the href of the WAI logo is `https://wai-aria-practices2.netlify.app/`

It should be `https://w3.org/wai/`

This seems like it would be a template bug, but the logo has the correct href on other sites using the template, e.g., https://www.w3.org/WAI/standards-guidelines/act/rules/

**Comment by richnoah** [comment]
@shawna-slh can you advise on where this would be governed in the template?  We have not been able to find any documentation to update it.

**Comment by shawna-slh** [comment]
I'm pretty sure it's just a ... [what's the right work? fluke? anomaly? bug? weakness?] in the system.

Reminder that the links don't always work as expected in the Netlify previews. That's the main reason we need to publish quietly and test before we announce or otherwise point people to it (per my e-mail earlier today).

I think you can close this issue for development, and flag it for QA once published.

**Comment by mcking65** [comment]
@shawna-slh wrote:

> I'm pretty sure it's just a ... [what's the right work? fluke? anomaly? bug? weakness?] in the system.
> 
> Reminder that the links don't always work as expected in the Netlify previews. That's the main reason we need to publish quietly and test before we announce or otherwise point people to it (per my e-mail earlier today).
> 
> I think you can close this issue for development, and flag it for QA once published.


I changed the title so it is now a test issue.

However, do we know what links are not expected to work in preview? The w3.org link works. Why can't this one work? It would be good to understand what can and can't work in preview for the purposes of quality control.
