### ISSUE TITLE
Files in /index [Required for Launch]

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-aria-practices#76]
This is more a question than something that necessarily needs to be fixed.

Is there a reason the files under `/index` are not in `/content/index`?  `/content` is the correct location for all files that are processed by Jeckyll and end up as pages. Unless they are a collection. 

But I see you have a mixture of Jekyll processed SSG source files and statically served files. As these are relative URIs I think it should be OK in the main site. Would have been good to have had time to test before launch.

Also I'm seeing an error 

` ERROR `/index/index.htmlexamples/js/jumpto.js' not found.`

This is seems to be saying the error in `/index/index.html` in is `examples/js/jumpto.js` not found (missing space)

The only ref to `jump.js` I find is  in the external repo .../aria-practices/examples/js/app.js

**Comment by mcking65** [comment]
@richnoah 

I don't know if this is related to our discussion yesterday, but I'd eventually like the URIs for the examples to be in examples directories that are children of the pattern directories.

For instance, for combobox examples, instead of the examples being in `/index/` like this:

~~~
/index/combobox/combobox-autocomplete-both.html
/index/combobox/combobox-autocomplete-list.html
/index/combobox/combobox-autocomplete-none.html
~~~

I'd like the URI path to be /patterns/PATTERN_DIR/examples, like this:

~~~
/patterns/combobox/examples/combobox/combobox-autocomplete-both.html
/patterns/combobox/examples/combobox/combobox-autocomplete-list.html
/patterns/combobox/examples/combobox/combobox-autocomplete-none.html
~~~

This will help re-enforce the relationship between a pattern and its examples.

**Comment by SteveALee** [comment]
FYI it occurred to me that the pattern source files could also be in in content/patterns/. But that's just my preference.

Jekyll is flexible and recurses down from content.

**Comment by richnoah** [comment]
@mcking65 yes, please create a separate issue for the URI work you mention.  That would not be required for launch and would be a separate body of work.  In speaking with Alex this would be a sizable lift.
